spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: keitaro.ono.1119@gmail.com
    password: npdxetwirlhxlxzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
  messages:
    basename: messages, ValidationMessages
    cache-duration: -1
    encoding: UTF-8
  jmx:
    default-domain: ex-emp
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  